OPENSHIFT_NAMESPACE: bb18ab
STAGE: dev

vaultNamespace: bb18ab-nonprod

pvc:
  spec:
    resources:
      requests:
        storage: 1Gi

deployment:
  spec:
    containers:
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 20m
          memory: 128Mi
