OPENSHIFT_NAMESPACE: bb18ab
STAGE: dev

vaultNamespace: bb18ab-nonprod

replicaCount: 1

pvc:
  spec:
    resources:
      requests:
        storage: 2Gi

deployment:
  spec:
    containers:
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 20m
          memory: 128Mi
