apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: postgres
  name: "postgres-{{ .Values.STAGE }}-hous-permit-portal"
  namespace: "{{ .Values.OPENSHIFT_NAMESPACE }}-{{ .Values.STAGE }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.pvc.spec.resources.requests.storage }}"
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
