apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: "{{ .Values.OPENSHIFT_NAMESPACE }}-{{ .Values.STAGE }}"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
    deployment: postgres
  sessionAffinity: None
  type: ClusterIP
