apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.STAGE }}-{{ .Values.appName }}"
  name: "{{ .Values.STAGE }}-{{ .Values.appName }}"
  namespace: "{{ .Values.OPENSHIFT_NAMESPACE }}-{{ .Values.STAGE }}"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: "{{ .Values.STAGE }}-{{ .Values.appName }}"
    deployment: "{{ .Values.STAGE }}-{{ .Values.appName }}"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
