---
openapi: 3.0.1
info:
  title: External API V1
  version: v1
  description: "This document describes the APIs available to external integrators
    to query and retrieve submitted permit applications.\nAdditional webhook events
    are also documented which will be sent to the url provided by the external integrator.\n\nThe
    submitted permit applications returned only include permit applications scoped
    to the jurisdiction of the API key used to authenticate the request.\n\nIf you
    would like to integrate with this API, please contact the Building Permit team
    to obtain an API key and submit your webhook url.\n\n### Authentication/Authorization
    \nAccess to the API is controlled by an API key. The API key is passed in the
    `Authorization` header as a Bearer token.\n\nNote: A new API key is required for
    each jurisdiction you would like to access.\n\n### Rate Limit\nThe API is rate
    limited to 100 requests per minute per API key and 300 requests per IP. If you
    exceed this limit, you will receive a 429 response.\n"
paths:
  "/permit_applications/search":
    post:
      summary: Lists paginated permit applications
      tags:
      - Permit applications
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    description: Submitted permit applications
                    items:
                      "$ref": "#/components/schemas/PermitApplication"
                  meta:
                    type: object
                    properties:
                      total_pages:
                        type: integer
                        description: Total number of pages
                      total_count:
                        type: integer
                        description: Total number of permit applications
                      current_page:
                        type: integer
                        description: Current page number
                    required:
                    - total_pages
                    - total_count
                    - current_page
                required:
                - data
                - meta
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResponseError"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              description: Filters permit applications by submitted date and permit
                classifications
              properties:
                permit_classifications:
                  description: Filters by permit classifications
                  type: string
                submitted_at:
                  type: object
                  description: Filters by submitted date
                  properties:
                    gt:
                      type: string
                      format: date-time
                      description: 'Greater than: submitted date is greater than this
                        date'
                    lt:
                      type: string
                      format: date-time
                      description: 'Less than: submitted date is less than this date'
                    gte:
                      type: string
                      format: date-time
                      description: 'Greater than or equal to: submitted date is greater
                        than or equal to this date'
                    lte:
                      type: string
                      format: date-time
                      description: 'Less than or equal to: submitted date is less
                        than or equal to this date'
  "/permit_applications/{id}":
    parameters:
    - name: id
      in: path
      description: Submitted permit application id
      required: true
      schema:
        type: string
    get:
      summary: requests are rate limited
      tags:
      - Permit applications
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/PermitApplication"
                required:
                - data
        '403':
          description: Accessing a permit application for unauthorized jurisdiction
        '404':
          description: Accessing a permit application which does not exist
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ResponseError"
basePath: "/external_api/v1"
servers:
- url: https:/buildingpermit.gov.bc.ca
  description: Production server
- url: "{serverUrl}"
  description: Server url
  variables:
    serverUrl:
      default: https:/buildingpermit.gov.bc.ca
tags:
- name: Permit applications
  description: Submitted permit applications (scoped to API key jurisdiction)
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: Bearer token
  schemas:
    PermitApplication:
      type: object
      properties:
        id:
          type: string
        full_address:
          type: string
          description: The full address of the permit application.
          nullable: true
        number:
          type: string
          description: The permit application number displayed to the user.
          nullable: true
        pid:
          type: string
          description: The PID of the permit application.
          nullable: true
        pin:
          type: string
          description: The PIN of the permit application.
          nullable: true
        reference_number:
          type: string
          description: The reference number of the permit application in external
            system.
          nullable: true
        submitted_at:
          type: number
          format: int64
          description: Datetime in milliseconds since the epoch (Unix time)
        permit_classifications:
          type: string
        permit_type:
          "$ref": "#/components/schemas/PermitClassification"
        activity:
          "$ref": "#/components/schemas/PermitClassification"
        submission_data:
          "$ref": "#/components/schemas/SubmissionData"
    SubmissionData:
      type: object
      description: 'The submitted permit application data. Note: the keys are the
        requirement block codes.'
      additionalProperties:
        type: object
        properties:
          id:
            type: string
          requirement_block_code:
            type: string
          name:
            type: string
          description:
            type: string
            nullable: true
          requirements:
            type: array
            descriptions: The requirements for this requirement block and their submitted
              values.
            items:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                requirement_code:
                  type: string
                  description: The requirement code for this requirement.
                type:
                  type: string
                  enum:
                  - text
                  - number
                  - checkbox
                  - select
                  - multi_option_select
                  - date
                  - textarea
                  - file
                  - phone
                  - email
                  - radio
                  - address
                  - bcaddress
                  - signature
                  - energy_step_code
                  - general_contact
                  - professional_contact
                  description: The input type for this requirement.
                value:
                  description: The submitted value for this requirement.
                  oneOf:
                  - type: string
                  - type: number
                  - type: boolean
                  - "$ref": "#/components/schemas/ContactSubmissionValue"
                  - "$ref": "#/components/schemas/MultiOptionSubmissionValue"
              required:
              - id
              - name
              - requirement_code
              - type
              - value
        required:
        - id
        - requirement_block_code
        - name
        - requirements
    PermitClassification:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
          nullable: true
        code:
          type: string
          description: The code of the permit classification.
    MultiOptionSubmissionValue:
      type: object
      additionalProperties:
        type: boolean
    ContactSubmissionValue:
      type: array
      items:
        type: object
        properties:
          first_name:
            type: string
            description: The first name of the contact.
          last_name:
            type: string
            description: The last name of the contact.
          email:
            type: string
            description: The email of the contact.
          phone:
            type: string
            description: The phone number of the contact.
          address:
            type: string
            description: The address of the contact.
          title:
            type: string
            description: The title of the contact.
          organization:
            type: string
            description: The organization of the contact.
    ResponseError:
      type: object
      properties:
        data:
          type: object
          properties: {}
        meta:
          type: object
          properties:
            message:
              type: string
              description: The error message.
            type:
              type: string
              enum:
              - error
formats:
- json
- yaml
security:
- Bearer: []
