STAGE: prod
vaultNamespace: "bb18ab-prod"

deployment:
  replicaCount: 1
  spec:
    containers:
      resources:
        requests:
          cpu: 150m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 512Mi
