OPENSHIFT_NAMESPACE: bb18ab
STAGE: dev
imageName: "consigno-server-automation"
appName: "consigno-verifio-notarius-server"

vaultNamespace: "bb18ab-nonprod"

deployment:
  replicaCount: 1
  spec:
    containers:
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 256Mi
