apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: "{{ .Values.STAGE }}-openshift-base"
  name: allow-from-openshift-ingress
  namespace: "{{ .Values.OPENSHIFT_NAMESPACE }}-{{ .Values.STAGE }}"
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
    - Ingress
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: "{{ .Values.STAGE }}-openshift-base"
  name: allow-same-namespace
  namespace: "{{ .Values.OPENSHIFT_NAMESPACE }}-{{ .Values.STAGE }}"
spec:
  ingress:
    - from:
        - podSelector: {}
  podSelector: {}
  policyTypes:
    - Ingress
status: {}
