apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: elasticsearch-template
parameters:
  - name: STAGE
    required: true
    value: test
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"elasticsearch:7.17.16"},"fieldPath":"spec.template.spec.containers[?(@.name==\"elasticsearch\")].image"}]'
      labels:
        app: elasticsearch
      name: elasticsearch
      namespace: bb18ab-${STAGE}
      resourceVersion: "8763541867"
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: elasticsearch
          deployment: elasticsearch
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-secret-secrets.env: bb18ab-nonprod/${STAGE}/elasticsearch
            vault.hashicorp.com/agent-inject-template-secrets.env: |
              {{- with secret "bb18ab-nonprod/${STAGE}/elasticsearch" }}
              {{- range $k, $v := .Data.data }}
              {{ $k }}={{ $v }}{{ end -}}
              {{- end  }}
            vault.hashicorp.com/agent-limits-cpu: 50m
            vault.hashicorp.com/agent-limits-mem: 100Mi
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-requests-cpu: 10m
            vault.hashicorp.com/agent-requests-mem: 25Mi
            vault.hashicorp.com/auth-path: auth/k8s-silver
            vault.hashicorp.com/namespace: platform-services
            vault.hashicorp.com/role: bb18ab-nonprod
          labels:
            app: elasticsearch
            deployment: elasticsearch
        spec:
          containers:
            - args:
                - /bin/bash
                - -c
                - |
                  set -a
                  . /vault/secrets/secrets.env
                  set +a
                  exec elasticsearch
              env:
                - name: discovery.type
                  value: single-node
                - name: xpack.security.enabled
                  value: "false"
              image: docker.io/library/elasticsearch@sha256:2701b3b14cede7427a1b1c431329d116c148b046e0fd51e1692ff4fc7b85609d
              imagePullPolicy: IfNotPresent
              name: elasticsearch
              ports:
                - containerPort: 9200
                  protocol: TCP
                - containerPort: 9300
                  protocol: TCP
              resources: {}
              terminationMessagePath: /${STAGE}/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /usr/share/elasticsearch/data
                  name: elasticsearch-data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: bb18ab-vault
          serviceAccountName: bb18ab-vault
          terminationGracePeriodSeconds: 30
          volumes:
            - name: elasticsearch-data
              persistentVolumeClaim:
                claimName: elasticsearch-${STAGE}-hous-permit-portal
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: elasticsearch
      name: elasticsearch
      namespace: bb18ab-${STAGE}
      resourceVersion: "8726822411"
    spec:
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: 9200-tcp
          port: 9200
          protocol: TCP
          targetPort: 9200
        - name: 9300-tcp
          port: 9300
          protocol: TCP
          targetPort: 9300
      selector:
        app: elasticsearch
        deployment: elasticsearch
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      finalizers:
        - kubernetes.io/pvc-protection
      labels:
        app: elasticsearch
      name: elasticsearch-${STAGE}-hous-permit-portal
      namespace: bb18ab-${STAGE}
      resourceVersion: "8765136528"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: netapp-file-standard
      volumeMode: Filesystem