apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: hous-permit-portal-template
parameters:
  - name: STAGE
    required: true
    value: test
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"${STAGE}-hous-permit-portal:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"${STAGE}-hous-permit-portal\")].image"}]'
      labels:
        app: ${STAGE}-hous-permit-portal
      name: ${STAGE}-hous-permit-portal
      namespace: bb18ab-${STAGE}
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: ${STAGE}-hous-permit-portal
          deployment: ${STAGE}-hous-permit-portal
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-secret-secrets.env: bb18ab-nonprod/${STAGE}/${STAGE}-hous-permit-portal
            vault.hashicorp.com/agent-inject-template-secrets.env: |
              {{- with secret "bb18ab-nonprod/${STAGE}/${STAGE}-hous-permit-portal" }}
              {{- range $k, $v := .Data.data }}
              {{ $k }}={{ $v }}{{ end -}}
              {{- end  }}
            vault.hashicorp.com/agent-limits-cpu: 50m
            vault.hashicorp.com/agent-limits-mem: 100Mi
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-requests-cpu: 10m
            vault.hashicorp.com/agent-requests-mem: 25Mi
            vault.hashicorp.com/auth-path: auth/k8s-silver
            vault.hashicorp.com/namespace: platform-services
            vault.hashicorp.com/role: bb18ab-nonprod
          labels:
            app: ${STAGE}-hous-permit-portal
            deployment: ${STAGE}-hous-permit-portal
        spec:
          containers:
            - image: image-registry.openshift-image-registry.svc:5000/bb18ab-${STAGE}/${STAGE}-hous-permit-portal@sha256:ae0ab92fc6eb1b337d5dfa8880f1968e4945a3de49725a308c73104f18b7957c
              imagePullPolicy: IfNotPresent
              name: ${STAGE}-hous-permit-portal
              ports:
                - containerPort: 3000
                  protocol: TCP
              resources:
                limits:
                  cpu: 100m
                  memory: 1Gi
                requests:
                  cpu: 50m
                  memory: 512Mi
              terminationMessagePath: /${STAGE}/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: bb18ab-vault
          serviceAccountName: bb18ab-vault
          terminationGracePeriodSeconds: 30
    status:
      availableReplicas: 1
      conditions:
        - lastTransitionTime: "2024-01-11T03:31:02Z"
          lastUpdateTime: "2024-01-15T23:16:54Z"
          message: ReplicaSet "${STAGE}-hous-permit-portal-5f44465b48" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: "True"
          type: Progressing
        - lastTransitionTime: "2024-01-16T17:42:57Z"
          lastUpdateTime: "2024-01-16T17:42:57Z"
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: "True"
          type: Available
      readyReplicas: 1
      replicas: 1
      updatedReplicas: 1
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${STAGE}-hous-permit-portal
      name: ${STAGE}-hous-permit-portal-route
      namespace: bb18ab-${STAGE}
    spec:
      host: ${STAGE}-hous-permit-portal.apps.silver.devops.gov.bc.ca
      port:
        targetPort: 3000-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${STAGE}-hous-permit-portal
        weight: 100
      wildcardPolicy: None
    status:
      ingress:
        - conditions:
            - lastTransitionTime: "2024-01-12T02:03:41Z"
              status: "True"
              type: Admitted
          host: ${STAGE}-hous-permit-portal.apps.silver.${STAGE}ops.gov.bc.ca
          routerCanonicalHostname: router-default.apps.silver.${STAGE}ops.gov.bc.ca
          routerName: default
          wildcardPolicy: None
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${STAGE}-hous-permit-portal
      name: ${STAGE}-hous-permit-portal
      namespace: bb18ab-${STAGE}
    spec:
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: 3000-tcp
          port: 3000
          protocol: TCP
          targetPort: 3000
      selector:
        app: ${STAGE}-hous-permit-portal
        deployment: ${STAGE}-hous-permit-portal
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      labels:
        app: ${STAGE}-hous-permit-portal
      name: allow-from-openshift-ingress
      namespace: bb18ab-${STAGE}
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector: {}
      policyTypes:
        - Ingress
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      labels:
        app: ${STAGE}-hous-permit-portal
      name: allow-same-namespace
      namespace: bb18ab-${STAGE}
    spec:
      ingress:
        - from:
            - podSelector: {}
      podSelector: {}
      policyTypes:
        - Ingress
    status: {}
