kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: compliance-log-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.pvc.spec.resources.requests.storage }}"
