apiVersion: batch/v1
kind: CronJob
metadata:
  name: purge-old-compliance-logfiles
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: 90-day-log-purger
              image: alpine:latest
              command: ["/bin/sh"]
              args: ["-c", "find /app/log -type f -mtime +1 -exec rm -f {} +"]
              volumeMounts:
                - name: compliance-log-pvc
                  mountPath: /log
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"
          restartPolicy: OnFailure
          volumes:
            - name: compliance-log-pvc
              persistentVolumeClaim:
                claimName: compliance-log-pvc
