apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.STAGE }}-{{ .Values.appName }}-web"
  name: "{{ .Values.STAGE }}-{{ .Values.appName }}-web"
  namespace: "{{ .Values.OPENSHIFT_NAMESPACE }}-{{ .Values.STAGE }}"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: "{{ .Values.STAGE }}-{{ .Values.appName }}-web"
    deployment: "{{ .Values.STAGE }}-{{ .Values.appName }}-web"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
