apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: "{{ .Values.OPENSHIFT_NAMESPACE }}-{{ .Values.STAGE }}"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
    deployment: redis
  sessionAffinity: None
  type: ClusterIP
