STAGE: test

route:
  spec:
    host: "test.buildingpermit.gov.bc.ca"

deployments:
  - process: web
    replicaCount: 1
    spec:
      containers:
        includeCommand: false
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
  - process: worker
    replicaCount: 1
    spec:
      containers:
        includeCommand: true
        args:
          - >-
            set -a; . /vault/secrets/secrets.env; set +a; exec bundle exec sidekiq
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 150m
            memory: 512Mi
  - process: anycable-rpc
    replicaCount: 1
    spec:
      containers:
        includeCommand: true
        args:
          - >-
            set -a; . /vault/secrets/secrets.env; set +a; exec bundle exec anycable --rpc-host=0.0.0.0:50051
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
