STAGE: prod

route:
  spec:
    host: "buildingpermit.gov.bc.ca"

vaultNamespace: "bb18ab-prod"

deployments:
  - process: web
    replicaCount: 2
    spec:
      containers:
        includeCommand: false
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
  - process: worker
    replicaCount: 2
    spec:
      containers:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
  - process: anycable-rpc
    replicaCount: 1
    spec:
      containers:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
