apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: "permit-portal-routing"
  name: "permit-portal-route"
spec:
  host: "{{ .Values.route.spec.host }}"
  port:
    targetPort: http
  # manage certs manually for now
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: "nginx"
    weight: 100
  wildcardPolicy: None
