name: Deploy main branch to dev

on:
  push:
    branches: ["derekyau/sc-66815/setup-github-actions-pipeline"]
    # branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres: # Example with PostgreSQL
        image: postgres:11
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"

      - name: Install Dependencies
        run: |
          bundle install

      - name: Setup Test Database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://user:password@localhost:5432/test_db
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Run RSpec
        run: |
          bundle exec rspec

    # build-and-push-image:
    #   runs-on: ubuntu-latest
    #   name: Build & Deploy Docker Rails / React application
    #   environment: dev
    #   ... [rest of your commented code] ...
