name: Pull Request Workflow

on:
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run RSpec Test Suite
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://user:password@localhost:5432/test_db
    services:
      postgres: # Example with PostgreSQL
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"

      - name: Install Dependencies
        run: |
          bundle install

      - name: Setup Test Database
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load

      - name: Run RSpec
        run: |
          bundle exec rspec
