name: Deploy a branch to TEST

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch Name"
        required: true
        default: "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build & Deploy Docker Rails / React application
    environment: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Build Docker Image
        uses: redhat-actions/buildah-build@v2
        with:
          image: test-hous-permit-portal
          tags: latest ${{ github.sha }}
          labels: |
            app=test-hous-permit-portal
            git-sha=${{ github.sha }}
          containerfiles: ./Dockerfile
          build-args: DEBUG_BUILD=true
      - name: Push to Openshift Registry using Service Account
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: test-hous-permit-portal
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.BUILDER_USERNAME }}
          password: ${{ secrets.BUILDER_TOKEN }}
